# -*- coding: utf-8 -*-
"""Análise Logs Moodle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8AoZ2n1561YcO1BFhE-WmcgkMpnUV5G
"""

import pandas as pd

# 1. Carregar os dados
caminho_arquivo = 'logs_INF01216 - U (232)_20260323-1019.xlsx'

try:
    df = pd.read_excel(caminho_arquivo)
except ValueError:
    df = pd.read_csv(caminho_arquivo)

# 2. Classificação de Eventos
# Evidências Ativas (Geração de artefato/nota para o cálculo da Proficiência)
eventos_ativos = [
    'Um envio foi submetido.',
    'Um arquivo foi enviado.',
    'Submissão criada.',
    'Tentativa do questionário entregue',
    'Post criado',
    'Discussão criada'
]

# Consideraremos como Engajamento Passivo (Esforço/Contexto) qualquer evento
# visualização de curso, recurso, pasta, status, etc.
eventos_excluidos = ['Usuário recebeu nota', 'Lista de usuários vistos', 'Perfil do usuário visto'] # Ruído administrativo puro

# 3. Dicionário de Mapeamento (Matriz de Rastreabilidade Expandida)
# Adicionei palavras-chave dos materiais de aula para capturar o engajamento passivo
def mapear_habilidade(contexto):
    contexto = str(contexto).lower()

    # h1: Decompor processos
    if any(k in contexto for k in ['descrever um processo', 'prática 1', 'introdução a bpm', 'identificação de processos']):
        return 'h1'

    # h2: Integrar eventos (temporais, mensagem, exceção)
    elif 'questionário - bpmn - parte 2' in contexto or 'questionário sobre a bpmn - parte 2' in contexto:
        return 'h2'

    # h4: Aplicar decisões exclusivas e inclusivas
    elif 'questionário- bpmn - parte 1' in contexto or 'questionário sobre bpmn - parte 1' in contexto:
        return 'h4'

    # h9: Desenhar processos utilizando BPMN
    elif any(k in contexto for k in ['etapa 1', 'etapa 2', 'enviar modelos camunda', 'prática 3', 'trabalho prático', 'modelagem de processos', 'camunda']):
        return 'h9'

    # h10: Integrar coreografias / interações BPMS
    elif 'etapa 3' in contexto:
        return 'h10'

    else:
        return 'Não Mapeado'

# Aplica o mapeamento e remove o ruído administrativo e itens não mapeados
df['Habilidade'] = df['Contexto do Evento'].apply(mapear_habilidade)
df_util = df[(df['Habilidade'] != 'Não Mapeado') & (~df['Nome do evento'].isin(eventos_excluidos))].copy()

# Cria uma coluna indicando o TIPO de rastro
df_util['Tipo_Rastro'] = df_util['Nome do evento'].apply(lambda x: 'Ativo (Proficiência)' if x in eventos_ativos else 'Passivo (Engajamento)')

# 4. Agregação de Dados
# Agrupando Ativos
df_ativos = df_util[df_util['Tipo_Rastro'] == 'Ativo (Proficiência)']
resumo_ativos = df_ativos.groupby('Habilidade').agg(
    Evidencias_Ativas=('Nome do evento', 'count'),
    Alunos_Ativos=('Nome completo', 'nunique')
).reset_index()

# Agrupando Passivos
df_passivos = df_util[df_util['Tipo_Rastro'] == 'Passivo (Engajamento)']
resumo_passivos = df_passivos.groupby('Habilidade').agg(
    Engajamento_Passivo=('Nome do evento', 'count'),
    Alunos_Passivos=('Nome completo', 'nunique')
).reset_index()

# Mesclando os dois resumos em uma tabela única
resumo_final = pd.merge(resumo_ativos, resumo_passivos, on='Habilidade', how='outer').fillna(0)

# Convertendo floats para inteiros (já que fillna coloca 0.0)
colunas_int = ['Evidencias_Ativas', 'Alunos_Ativos', 'Engajamento_Passivo', 'Alunos_Passivos']
resumo_final[colunas_int] = resumo_final[colunas_int].astype(int)

# Ordenando pelo total de evidências ativas
resumo_final = resumo_final.sort_values(by='Evidencias_Ativas', ascending=False)

# 5. Análise de Lacunas (Gaps)
todas_habilidades = {f'h{i}' for i in range(1, 11)}
habilidades_encontradas = set(resumo_final['Habilidade'].unique())
gaps = todas_habilidades - habilidades_encontradas

df_gaps = pd.DataFrame({'Habilidades_Sem_Cobertura': list(gaps)})
if df_gaps.empty:
    df_gaps = pd.DataFrame({'Habilidades_Sem_Cobertura': ['Nenhuma lacuna encontrada.']})

# 6. Exportando para Excel (Para usar como evidência na Tese)
nome_arquivo_saida = 'evidencias_framework_moodle.xlsx'

with pd.ExcelWriter(nome_arquivo_saida, engine='openpyxl') as writer:
    resumo_final.to_excel(writer, sheet_name='Analise_Habilidades', index=False)
    df_gaps.to_excel(writer, sheet_name='Analise_Gaps', index=False)

print(f"Análise concluída com sucesso!")
print(f"Os resultados foram salvos no arquivo: {nome_arquivo_saida}")
print("\n=== PRÉVIA DOS RESULTADOS ===")
print(resumo_final.to_string(index=False))

